// prettier-ignore
class TagsHelper {
  static const Map<String, List<String>> sugestoesPorCategoria = {
    // MARK: - Mercearia Doce
    'Mercearia Doce': [
      'açúcar',
      'chocolate',
      'biscoito',
      'geleia',
      'achocolatado',
      'leite condensado',
      'creme de leite',
      'confeitaria',
      'mel',
      'goma',
      'doce',
      'sobremesa',
      'bala',
      'chiclete',
      'marshmallow',
      'paçoca',
      'doce de leite',
      'granulado',
      'cobertura',
      'wafer',
      'pipoca doce',
      'achocolatado em pó',
      'goiabada',
      'creme de avelã',
      'gelatina',
      'amendoim confeitado',
      'pudim',
      'flan',
      'sagu',
      'coco ralado',
      'essência de baunilha',
      'fermento biológico',
      'fermento químico',
      'pasta americana',
      'confeito',
      'calda de sorvete',
      'adoçante',
      'fruta em calda',
      'pêssego em calda',
      'figo em calda',
      'cookies'
    ],
    // MARK: - Mercearia Salgada
    'Mercearia Salgada': [
      'arroz',
      'feijão',
      'macarrão',
      'óleo',
      'molho de tomate',
      'farinha',
      'sal',
      'tempero',
      'conservas',
      'enlatados',
      'azeite',
      'vinagre',
      'maionese',
      'ketchup',
      'mostarda',
      'milho',
      'ervilha',
      'sardinha',
      'macarrão instantâneo',
      'farinha de trigo',
      'salgadinho',
      'pipoca',
      'atum em conserva',
      'grão de bico',
      'lentilha',
      'polvilho doce',
      'polvilho azedo',
      'farinha de mandioca',
      'farinha de milho',
      'cuscuz',
      'fubá',
      'caldo de galinha',
      'caldo de carne',
      'molho de pimenta',
      'shoyu',
      'molho inglês',
      'azeitona',
      'palmito',
      'cogumelo',
      'seleta de legumes',
      'extrato de tomate',
      'massa de lasanha'
    ],
    // MARK: - Bebidas
    'Bebidas': [
      'refrigerante',
      'suco',
      'água',
      'energético',
      'isotônico',
      'néctar',
      'chá gelado',
      'água de coco',
      'refresco',
      'zero açúcar',
      'tônica',
      'gelada',
      'suco natural',
      'xarope',
      'chá pronto',
      'água com gás',
      'suco de uva',
      'refrigerante lata',
      'achocolatado pronto',
      'guaraná',
      'bebida de soja',
      'suco de caixinha',
      'água mineral',
      'gasosa',
      'suco concentrado',
      'suco detox',
      'chá de saquinho',
      'mate',
      'suco em pó',
      'refresco de fruta',
      'limonada',
      'bebida láctea',
      'água tônica',
      'suco integral',
      'smoothie',
      'suco de laranja',
      'suco de maçã',
      'suco de pêssego',
      'suco de manga',
      'suco de caju'
    ],
    // MARK: - Adega
    'Adega': [
      'vinho',
      'cerveja',
      'artesanal',
      'whisky',
      'espumante',
      'vodka',
      'gin',
      'cachaça',
      'aperitivo',
      'destilado',
      'vinho tinto',
      'pilsen',
      'vinho branco',
      'ipa',
      'saquê',
      'tequila',
      'licor',
      'conhaque',
      'rum',
      'espumante brut',
      'ice',
      'espumante moscatel',
      'vinho rosé',
      'vinho seco',
      'vinho suave',
      'cerveja puro malte',
      'cerveja zero',
      'espumante demi-sec',
      'vinhos importados',
      'espumante rosé',
      'malbec',
      'cabernet sauvignon',
      'merlot',
      'chardonnay',
      'stout',
      'weiss',
      'lager',
      'chopp',
      'conhaque de alcatrão',
      'steinhäger'
    ],
    // MARK: - Frios Laticinios
    'Frios e Laticínios': [
      'queijo',
      'presunto',
      'iogurte',
      'manteiga',
      'requeijão',
      'salame',
      'margarina',
      'mortadela',
      'coalhada',
      'fatiados',
      'queijo muçarela',
      'queijo prato',
      'parmesão',
      'peito de peru',
      'leite fermentado',
      'petit suisse',
      'cream cheese',
      'ricota',
      'provolone',
      'leite fresco',
      'queijo minas',
      'queijo cheddar',
      'queijo coalho',
      'salame italiano',
      'mortadela defumada',
      'blanquet',
      'copa',
      'lombo defumado',
      'patê',
      'iogurte grego',
      'iogurte natural',
      'leite desnatado',
      'leite sem',
      'leite integral',
      'queijo gorgonzola',
      'queijo brie',
      'queijo gouda',
      'queijo estepe',
      'requeijão cremoso',
      'manteiga com sal'
    ],
    // MARK: - limpeza
    'Limpeza': [
      'detergente',
      'sabão em pó',
      'desinfetante',
      'amaciante',
      'multiuso',
      'cloro',
      'esponja',
      'vassoura',
      'saco de lixo',
      'desengordurante',
      'sabão em barra',
      'água sanitária',
      'limpa vidros',
      'lustra móveis',
      'inseticida',
      'rodo',
      'pano de prato',
      'limpa piso',
      'tira manchas',
      'soda cáustica',
      'amaciante concentrado',
      'limpa cerâmica',
      'álcool',
      'pastilha sanitária',
      'removedor',
      'limpa inox',
      'limpa carpetes',
      'bloqueador de odores',
      'pano multiuso',
      'palha de aço',
      'escova',
      'balde',
      'mop',
      'saco para pia',
      'desodorizador',
      'limpa couro',
      'sabão líquido',
      'alvejante',
      'querosene',
      'limpa pedras'
    ],
    // MARK: - Higiene
    'Higiene Pessoal': [
      'shampoo',
      'sabonete',
      'creme dental',
      'desodorante',
      'fio dental',
      'condicionador',
      'absorvente',
      'papel higiênico',
      'barba',
      'algodão',
      'enxaguante bucal',
      'escova de dentes',
      'sabonete líquido',
      'gel',
      'hastes flexíveis',
      'lâmina de barbear',
      'protetor diário',
      'talco',
      'esfoliante',
      'lenço de papel',
      'creme de barbear',
      'pós barba',
      'máscara capilar',
      'creme para pentear',
      'sabonete íntimo',
      'serum',
      'espuma de barbear',
      'creme para mãos',
      'creme para pés',
      'tônico',
      'lenço umedecido',
      'hidratante corporal',
      'curativo',
      'cotonete',
      'touca de banho',
      'pente',
      'escova de cabelo',
      'presilha',
      'elástico'
    ],
    // MARK: - Hortifrutti
    'Hortifruti': [
      'fruta',
      'legumes',
      'verdura',
      'fresco',
      'orgânico',
      'folhas',
      'raiz',
      'ovos',
      'saudável',
      'natural',
      'batata',
      'cebola',
      'alho',
      'tomate',
      'alface',
      'banana',
      'maçã',
      'laranja',
      'cenoura',
      'uvas',
      'temperos frescos',
      'pimentão',
      'abobrinha',
      'chuchu',
      'berinjela',
      'brócolis',
      'couve-flor',
      'couve',
      'espinafre',
      'rúcula',
      'salsa',
      'cebolinha',
      'manjericão',
      'limão',
      'mamão',
      'melancia',
      'melão',
      'abacaxi',
      'manga',
      'morango',
      'pera',
      'kiwi',
      'ovos de codorna'
    ],
    // MARK: - Açougue
    'Açougue': [
      'carne bovina',
      'frango',
      'suíno',
      'linguiça',
      'churrasco',
      'bife',
      'moída',
      'costela',
      'frutos do mar',
      'espetinho',
      'picanha',
      'bacon',
      'alcatra',
      'coxinha da asa',
      'peito de frango',
      'pernil',
      'cordeiro',
      'peixe',
      'hambúrguer artesanal',
      'carne seca',
      'contra filé',
      'cupim',
      'maminha',
      'fraldinha',
      'lagarto',
      'patinho',
      'coxão mole',
      'sassami',
      'coxão duro',
      'músculo',
      'acém',
      'filé de peito',
      'sobrecoxa',
      'asa',
      'coração de frango',
      'linguiça toscana',
      'linguiça calabresa',
      'paio',
      'costelinha suína',
      'lombo suíno'
    ],
    // MARK: - Padaria
    'Padaria': [
      'pão francês',
      'bolo',
      'salgado',
      'pão de forma',
      'doce',
      'broa',
      'artesanal',
      'rosca',
      'bisnaguinha',
      'café da manhã',
      'baguete',
      'confeitaria',
      'pão de queijo',
      'sonho',
      'carolinas',
      'tortas',
      'pão integral',
      'croissant',
      'pudim',
      'biscoito de polvilho',
      'fubá',
      'pão de milho',
      'pão sovado',
      'pão de hambúrguer',
      'pão de cachorro',
      'quiche',
      'empada',
      'folhado',
      'donut',
      'muffin',
      'cookie',
      'brioche',
      'ciabatta',
      'pão australiano',
      'pão de coco',
      'pão de mel',
      'tapioca',
      'beiju',
      'pão de batata',
      'torrada artesanal'
    ],
    // MARK: - Rotisseria
    'Rotisseria': [
      'frango assado',
      'lasanha',
      'maionese',
      'marmita',
      'pronto',
      'quibe',
      'assado',
      'empadão',
      'salada',
      'guarnição',
      'massas prontas',
      'farofa',
      'nhoque',
      'canelone',
      'feijoada',
      'arroz carreteiro',
      'coxinha',
      'risoto',
      'parmegiana',
      'strogonoff',
      'panqueca',
      'rondelli',
      'iscas',
      'frango frito',
      'batata rústica',
      'legumes assados',
      'arroz branco',
      'arroz à grega',
      'tutu de feijão',
      'macarronese',
      'salpicão',
      'bife',
      'medalhão',
      'sobrecoxa assada',
      'costela assada',
      'peixe frito',
      'bolinho de bacalhau',
      'pastel',
      'enroladinho',
      'torta salgada'
    ],
    // MARK: - Pet Shop
    'Pet Shop': [
      'ração',
      'cão',
      'gato',
      'petisco',
      'areia sanitária',
      'brinquedo',
      'higiene pet',
      'coleira',
      'filhote',
      'adulto',
      'ração úmida',
      'guia',
      'shampoo pet',
      'antipulga',
      'tapete higiênico',
      'pássaro',
      'peixe',
      'comedouro',
      'ossinho',
      'transporte',
      'bebedouro',
      'arranhador',
      'cama pet',
      'escova pet',
      'cortador de unha',
      'perfume pet',
      'sachê',
      'ração castrados',
      'ração raças pequenas',
      'ração premium',
      'osso',
      'brinquedo corda',
      'bolinha',
      'coleira peitoral',
      'focinheira',
      'medicamento pet',
      'vitamina pet',
      'areia de gato',
      'pipi pode'
    ],
    // MARK: - Bazar
    'Bazar': [
      'pilha',
      'lâmpada',
      'fósforo',
      'isqueiro',
      'utilidades',
      'presente',
      'vela',
      'guarda-chuva',
      'ferramenta',
      'casa',
      'extensão',
      'balde',
      'adaptador',
      'fita adesiva',
      'gancho',
      'cadeado',
      'pilha alcalina',
      'varal',
      'pregador',
      'caixa organizadora',
      'cabide',
      'caneta',
      'cola',
      'tesoura',
      'baralho',
      'vela de aniversário',
      'filtro de café',
      'papel',
      'papel alumínio',
      'filme pvc',
      'papel manteiga',
      'guardanapo',
      'copo',
      'prato descartável',
      'talher descartável',
      'espeto',
      'carvão',
      'grelha',
      'acendedor',
      'isopor'
    ],
    // MARK: - Congelados
    'Congelados': [
      'pizza',
      'nuggets',
      'sorvete',
      'polpa de fruta',
      'hambúrguer',
      'açaí',
      'batata frita',
      'pão de queijo',
      'refeição pronta',
      'vegetais',
      'lasanha congelada',
      'steaks',
      'picolé',
      'mandioca',
      'massa',
      'salgadinhos congelados',
      'frutas congeladas',
      'peixe congelado',
      'anéis de cebola',
      'tortas congeladas',
      'sorvete de massa',
      'pão',
      'coxinha congelada',
      'kibe congelado',
      'pão de alho',
      'waffle',
      'pão de queijo recheado',
      'frango empanado',
      'isca de peixe',
      'caldo',
      'sopa congelada',
      'feijoada congelada',
      'yakisoba',
      'comida japonesa',
      'frutas vermelhas',
      'amora congelada',
      'morango congelado',
      'brócolis'
    ],
    // MARK: - Bebê
    'Bebê': [
      'fralda',
      'lenço umedecido',
      'fórmula infantil',
      'pomada',
      'chupeta',
      'mamadeira',
      'shampoo bebê',
      'papinha',
      'banho',
      'cuidados',
      'talco',
      'condicionador bebê',
      'talco bebê',
      'colônia bebê',
      'mordedor',
      'babador',
      'sabonete líquido bebê',
      'hastes seguras',
      'roupa',
      'copo de treinamento',
      'roupa de bebê',
      'brinquedo educativo',
      'porta leite em pó',
      'escova de mamadeira',
      'aspirador nasal',
      'termômetro',
      'banheira',
      'toalha de banho',
      'cueiro',
      'manta',
      'meia bebê',
      'sapatinho',
      'sabonete em barra',
      'óleo bebê',
      'creme',
      'loção hidratante',
      'shampoo neutro',
      'fralda de pano',
      'fralda gg'
    ],
    // MARK: - Saude Suplementos
    'Saúde e Suplementos': [
      'whey protein',
      'creatina',
      'vitamina',
      'ômega 3',
      'pré-treino',
      'barra de proteína',
      'colágeno',
      'emagrecimento',
      'performance',
      'massa',
      'bcaa',
      'glutamina',
      'multivitamínico',
      'hipercalórico',
      'albumina',
      'suplemento vegano',
      'termogênico',
      'magnésio',
      'zma',
      'pastilha de vitamina c',
      'arginina',
      'beta-alanina',
      'cafeína',
      'pasta de amendoim',
      'cloreto de magnésio',
      'vitamina d',
      'cálcio',
      'ferro',
      'zinco',
      'suplemento alimentar',
      'shake diet',
      'chá seca',
      'melatonina',
      'triptofano',
      'óleo de coco',
      'chia',
      'linhaça',
      'psyllium',
      'levedura de cerveja',
      'espironolactona',
      'creatina mono'
    ],
    // MARK: - Farmacia
    'Farmácia': [
      'medicamento',
      'curativo',
      'termômetro',
      'primeiros socorros',
      'analgésico',
      'vitamina',
      'máscara',
      'álcool em pó',
      'antisséptico',
      'gaze',
      'band-aid',
      'esparadrapo',
      'soro fisiológico',
      'antiácido',
      'anti-inflamatório',
      'preservativo',
      'teste de gravidez',
      'algodão',
      'algodão em bola',
      'pastilha garganta',
      'repelente',
      'gel secativo',
      'água oxigenada',
      'iodo',
      'solução nasal',
      'colírio',
      'pomada',
      'inalador',
      'nebulizador',
      'medidor de pressão',
      'teste glicemia',
      'lanceta',
      'algodão quadrado',
      'hastes de algodão',
      'máscara pff2',
      'luva de procedimento',
      'suplemento mineral',
      'vitamina e',
      'cloreto'
    ],
    // MARK: - Perfumaria
    'Perfumaria': [
      'maquiagem',
      'perfume',
      'creme facial',
      ' hidratante',
      'esmaltes',
      'protetor solar',
      'estética',
      'beleza',
      'batom',
      'máscara',
      'rímel',
      'base facial',
      'delineador',
      'removedor de esmalte',
      'água micelar',
      'sérum',
      'óleo corporal',
      'bronzeador',
      'corretivo',
      'fixador',
      'pó compacto',
      'iluminador',
      'blush',
      'sombra',
      'lápis de olho',
      'lápis de boca',
      'gloss',
      'bruma fixadora',
      'primer',
      'cilios',
      'pinça',
      'curvex',
      'esponja de maquiagem',
      'pincel de maquiagem',
      'shampoo a seco',
      'reparador de pontas',
      'fixador de cabelo',
      'laquê'
    ],
    // MARK: - floricultura
    'Floricultura': [
      'flores',
      'vaso',
      'adubo',
      'terra',
      'plantas',
      'presente',
      'buquê',
      'jardinagem',
      'semente',
      'decoração',
      'orquídea',
      'suculenta',
      'rosa',
      'ferramenta jardim',
      'regador',
      'cachepô',
      'folhagem',
      'substrato',
      'pesticida natural',
      'muda',
      'vaso de barro',
      'vaso de plástico',
      'pratinho',
      'pedrisco',
      'argila expandida',
      'casca de pinus',
      'pau',
      'humus de minhoca',
      'fertilizante líquido',
      'poda',
      'tesoura poda',
      'luva jardim',
      'girassol',
      'margarida',
      'antúrio',
      'lírio',
      'samambaia',
      'jibóia',
      'cacto',
      'violeta',
      'fertilizante foliar'
    ],
    // MARK: - Casa Utensilios
    'Casa e Utensílios': [
      'panela',
      'talher',
      'copo',
      'prato',
      'organizador',
      'assadeira',
      'pote',
      'limpeza profunda',
      'cozinha',
      'decorativo',
      'frigideira',
      'abridor',
      'escorredor',
      'tábua de carne',
      'jarra',
      'xícara',
      'fouet',
      'tupperware',
      'peneira',
      'ralador',
      'concha',
      'escumadeira',
      'garfo',
      'faca de chef',
      'faca de pão',
      'colher de pau',
      'espátula',
      'forma',
      'forma de bolo',
      'forma de pizza',
      'leiteira',
      'cuscuzeira',
      'bule',
      'garrafa térmica',
      'saladeira',
      'fruteira',
      'porta tempero',
      'pote de',
      'lixeira de cozinha',
      'dispenser',
      'escorredor de pratos'
    ],
    // MARK: - Papelaria
    'Papelaria': [
      'caderno',
      'caneta',
      'papel A4',
      'pasta',
      'lápis',
      'borracha',
      'mochila',
      'escritório',
      'escolar',
      'envelope',
      'corretivo',
      'régua',
      'canetinha',
      'tesoura',
      'grampeador',
      'fita adesiva',
      'calculadora',
      'bloco de notas',
      'apontador',
      'marca texto',
      'post-it',
      'grafite',
      'lapiseira',
      'tinta guache',
      'pincel escolar',
      'cartolina',
      'papel',
      'papel de seda',
      'papel crepom',
      'cola branca',
      'cola bastão',
      'clipe',
      'elástico de borracha',
      'perfurador',
      'estilete',
      'agenda',
      'fichário',
      'divisor de pasta',
      'organizador de mesa',
      'estojo'
    ],
    // MARK: - Informatica
    'Eletro e Informática': [
      'mouse',
      'teclado',
      'fone de ouvido',
      'carregador',
      'cabo usb',
      'pilha',
      'bateria',
      'eletroportáteis',
      'ventilador',
      'suporte',
      'caixa de som',
      'pendrive',
      'power bank',
      'roteador',
      'headset',
      'liquidificador',
      'batedeira',
      'sanduicheira',
      'ferro de passar',
      'cafeteira',
      'micro-ondas',
      'air fryer',
      'mixer',
      'processador',
      'espremedor',
      'torradeira',
      'grill',
      'panela elétrica',
      'extensão',
      'filtro de linha',
      'adaptador de tomada',
      'cartão de memória',
      'hd',
      'webcam',
      'monitor',
      'estabilizador',
      'calculadora científica'
    ],
    // MARK: - Ferramentas e Jardim
    'Ferramentas e Jardim': [
      'martelo',
      'chave de fenda',
      'mangueira',
      'vaso',
      'trena',
      'prego',
      'parafuso',
      'alicates',
      'jardim',
      'reforma',
      'manutenção',
      'buchas',
      'furadeira',
      'serrote',
      'luva de proteção',
      'escada',
      'tinta',
      'pincel',
      'chave inglesa',
      'nível',
      'chave philips',
      'chave biela',
      'estilete profissional',
      'fita isolante',
      'fita veda rosca',
      'cola',
      'broca',
      'disco de corte',
      'lixa',
      'rolo de pintura',
      'espátula',
      'massa corrida',
      'silicone',
      'vassoura de jardim',
      'ancinho',
      'pá',
      'enxada',
      'pulverizador',
      'grampeador tapeceiro'
    ],
    // MARK: Vestuario
    'Vestuário': [
      'camiseta',
      'meia',
      'chinelo',
      'cueca',
      'calcinha',
      'bermuda',
      'pijama',
      'acessórios',
      'moda',
      'básico',
      'regata',
      'top',
      'shorts',
      'moletom',
      'boné',
      'cinto',
      'sandália',
      'sapatilha',
      'calça',
      'saia',
      'agasalho',
      'jaqueta',
      'blusa',
      'vestido',
      'legging',
      'body',
      'sutiã',
      'meia calça',
      'meia soquete',
      'meia social',
      'chinelo de quarto',
      'sunga',
      'biquíni',
      'saída de praia',
      'lenço',
      'cachecol',
      'luva',
      'touca de lã',
      'avental',
      'uniforme'
    ],
    // MARK: Jogos Brinquedos
    'Brinquedos e Jogos': [
      'boneca',
      'carrinho',
      'tabuleiro',
      'quebra-cabeça',
      'educativo',
      'pelúcia',
      'infantil',
      'diversão',
      'card game',
      'lego',
      'massinha',
      'bolinha de gude',
      'iôiô',
      'piscina de bolinha',
      'fantoche',
      'slime',
      'bicicleta',
      'patins',
      'lançador',
      'quebra-cabeça 3d',
      'dominó',
      'baralho',
      'xadrez',
      'dama',
      'pula corda',
      'bolha de sabão',
      'peão',
      'peteca',
      'triciclo',
      'patinete',
      'skate',
      'bola de futebol',
      'boia',
      'bola de vôlei',
      'raquete',
      'kit praia',
      'cozinha infantil',
      'boneco',
      'heróis',
      'dinossauro'
    ],
    // MARK: Tabacaria
    'Tabacaria': [
      'isqueiro',
      'seda',
      'tabaco',
      'carvão',
      'essência',
      'palheiro',
      'filtro',
      'narguilé',
      'acessórios',
      'fumo',
      'dichavador',
      'cinzeiro',
      'piteira',
      'charuto',
      'fluido isqueiro',
      'bolador',
      'maçarico',
      'tabaco orgânico',
      'cliper',
      'porta cigarro',
      'isqueiro maçarico',
      'seda de vidro',
      'cuia',
      'tesoura tabaco',
      'filtro de carvão',
      'bag',
      'incenso',
      'porta fumo',
      'limpador de narguilé',
      'fogareiro',
      'vaper',
      'juice',
      'coil',
      'algodão tabacaria',
      'piteira de vidro',
      'hash',
      'slick',
      'bandeja',
      'isqueiro elétrico',
      'cachimbo'
    ],
    // MARK: Festas Decoracao
    'Festas e Decoração': [
      'balão',
      'descartáveis',
      'enfeite',
      'velas festa',
      'painel',
      'kit',
      'lembrancinha',
      'confeitaria',
      'aniversário',
      'fantasia',
      'confete',
      'temático',
      'copo descartável',
      'prato descartável',
      'toalha de mesa',
      'serpentina',
      'chapéu de festa',
      'painel decorativo',
      'cachepô festa',
      'marshmallow festa',
      'kit festa',
      'lanterna',
      'pisca-pisca',
      'fitas',
      'balão metalizado',
      'bomba de balão',
      'forminha de doce',
      'suporte',
      'topo de bolo',
      'vela palito',
      'vela faísca',
      'saquinho surpresa',
      'tiara',
      'máscara festa',
      'adereço',
      'buzina',
      'língua de sogra',
      'pinhata',
      'tubete',
      'latinha'
    ],
    // MARK: Automotivo
    'Automotivo': [
      'óleo motor',
      'cera',
      'aditivo',
      'aromatizante',
      'limpeza carro',
      'estopa',
      'pneu',
      'palheta',
      'fluido',
      'manutenção',
      'pretinho',
      'shampoo automotivo',
      'limpa pneu',
      'silicone líquido',
      'fusível',
      'chave de roda',
      'triângulo',
      'extintor',
      'macaco',
      'água radiador',
      'fluido de freio',
      'limpa parabrisa',
      'esponja automotiva',
      'capa',
      'limpa estofado',
      'renovador de plásticos',
      'desengripante',
      'graxa',
      'estopa de polimento',
      'flanela de microfibra',
      'carregador bateria',
      'cabo de transferência',
      'suporte celular carro',
      'tapete carro',
      'antena',
      'calota',
      'lâmpada automotiva',
      'palheta traseira'
    ],
    // MARK: Outros
    'Outros': [
      'diversos',
      'variados',
      'utilidades',
      'geral',
      'sem categoria',
      'oferta',
      'novidade',
      'importado',
      'presente',
      'promocional',
      'exclusivo',
      'queima de estoque',
      'lançamento',
      'mais vendidos',
      'sustentável',
      'econômico',
      'atacado',
      'varejo',
      'premium',
      'eco',
      'colecionável',
      'artigo sazonal',
      'itinerante',
      'venda rápida',
      'oportunidade',
      'sortido',
      'kit promocional',
      'pague menos',
      'leve',
      'produto do mês',
      'indispensável',
      'casa e lazer',
      'curiosidades',
      'tendência',
      'essencial',
      'praticidade',
      'estilo de vida',
      'best',
      'top de linha',
      'custo benefício'
    ],
  };
}
