// models/tags_helper.dart

class TagsHelper {
  static const Map<String, List<String>> sugestoesPorCategoria = {
    'Mercearia Doce': [
      'açúcar',
      'chocolate',
      'biscoito',
      'geleia',
      'achocolatado',
      'leite condensado',
      'creme de leite',
      'confeitaria',
      'mel',
      'goma',
      'doce',
      'sobremesa',
      'bala',
      'chiclete',
      'marshmallow',
      'paçoca',
      'doce de leite',
      'granulado',
      'cobertura',
      'wafer',
      'pipoca doce',
      'achocolatado em pó',
      'goiabada'
    ],
    'Mercearia Salgada': [
      'arroz',
      'feijão',
      'macarrão',
      'óleo',
      'molho de tomate',
      'farinha',
      'sal',
      'tempero',
      'conservas',
      'enlatados',
      'azeite',
      'vinagre',
      'maionese',
      'ketchup',
      'mostarda',
      'milho',
      'ervilha',
      'sardinha',
      'macarrão instantâneo',
      'farinha de trigo',
      'salgadinho',
      'pipoca'
    ],
    'Bebidas': [
      'refrigerante',
      'suco',
      'água',
      'energético',
      'isotônico',
      'chá gelado',
      'água de coco',
      'refresco',
      'zero açúcar',
      'gelada',
      'tônica',
      'suco natural',
      'néctar',
      'xarope',
      'chá pronto',
      'água com gás',
      'suco de uva',
      'refrigerante lata',
      'achocolatado pronto',
      'bebida de soja'
    ],
    'Adega': [
      'vinho',
      'cerveja',
      'artesanal',
      'whisky',
      'espumante',
      'vodka',
      'gin',
      'cachaça',
      'aperitivo',
      'destilado',
      'vinho tinto',
      'vinho branco',
      'pilsen',
      'ipa',
      'saquê',
      'tequila',
      'licor',
      'conhaque',
      'rum',
      'espumante brut',
      'ice',
      'espumante moscatel'
    ],
    'Frios e Laticínios': [
      'queijo',
      'presunto',
      'iogurte',
      'manteiga',
      'requeijão',
      'margarina',
      'salame',
      'mortadela',
      'coalhada',
      'fatiados',
      'queijo muçarela',
      'queijo prato',
      'parmesão',
      'peito de peru',
      'leite fermentado',
      'petit suisse',
      'cream cheese',
      'ricota',
      'provolone',
      'leite fresco'
    ],
    'Limpeza': [
      'detergente',
      'sabão em pó',
      'desinfetante',
      'amaciante',
      'multiuso',
      'cloro',
      'esponja',
      'vassoura',
      'saco de lixo',
      'desengordurante',
      'sabão em barra',
      'água sanitária',
      'limpa vidros',
      'lustra móveis',
      'inseticida',
      'rodo',
      'pano de prato',
      'limpa piso',
      'tira manchas',
      'soda cáustica',
      'amaciante concentrado'
    ],
    'Higiene Pessoal': [
      'shampoo',
      'sabonete',
      'creme dental',
      'desodorante',
      'condicionador',
      'fio dental',
      'absorvente',
      'papel higiênico',
      'barba',
      'algodão',
      'enxaguante bucal',
      'escova de dentes',
      'sabonete líquido',
      'hastes flexíveis',
      'lâmina de barbear',
      'protetor diário',
      'talco',
      'gel de cabelo',
      'esfoliante',
      'lenço de papel'
    ],
    'Hortifruti': [
      'fruta',
      'legumes',
      'verdura',
      'fresco',
      'orgânico',
      'folhas',
      'raiz',
      'ovos',
      'saudável',
      'natural',
      'batata',
      'cebola',
      'alho',
      'tomate',
      'alface',
      'banana',
      'maçã',
      'laranja',
      'cenoura',
      'temperos frescos',
      'pimentão'
    ],
    'Açougue': [
      'carne bovina',
      'frango',
      'suíno',
      'linguiça',
      'churrasco',
      'bife',
      'moída',
      'costela',
      'frutos do mar',
      'espetinho',
      'picanha',
      'alcatra',
      'coxinha da asa',
      'peito de frango',
      'pernil',
      'bacon',
      'cordeiro',
      'peixe',
      'hambúrguer artesanal',
      'carne seca'
    ],
    'Padaria': [
      'pão francês',
      'bolo',
      'salgado',
      'pão de forma',
      'doce',
      'artesanal',
      'rosca',
      'bisnaguinha',
      'café da manhã',
      'confeitaria',
      'pão de queijo',
      'baguete',
      'sonho',
      'carolinas',
      'tortas',
      'pão integral',
      'croissant',
      'broa',
      'pudim',
      'biscoito de polvilho'
    ],
    'Rotisseria': [
      'frango assado',
      'lasanha',
      'maionese',
      'marmita',
      'pronto',
      'assado',
      'empadão',
      'salada',
      'guarnição',
      'massas prontas',
      'nhoque',
      'canelone',
      'feijoada',
      'arroz carreteiro',
      'quibe',
      'coxinha',
      'risoto',
      'parmegiana',
      'farofa',
      'strogonoff'
    ],
    'Pet Shop': [
      'ração',
      'cão',
      'gato',
      'petisco',
      'areia sanitária',
      'brinquedo',
      'higiene pet',
      'coleira',
      'filhote',
      'adulto',
      'ração úmida',
      'shampoo pet',
      'antipulga',
      'tapete higiênico',
      'pássaro',
      'peixe',
      'comedouro',
      'guia',
      'ossinho',
      'transporte'
    ],
    'Bazar': [
      'pilha',
      'lâmpada',
      'fósforo',
      'isqueiro',
      'utilidades',
      'presente',
      'vela',
      'guarda-chuva',
      'ferramenta',
      'casa',
      'extensão',
      'adaptador',
      'fita adesiva',
      'gancho',
      'cadeado',
      'pilha alcalina',
      'varal',
      'pregador',
      'caixa organizadora',
      'balde'
    ],
    'Congelados': [
      'pizza',
      'nuggets',
      'sorvete',
      'polpa de fruta',
      'hambúrguer',
      'batata frita',
      'pão de queijo',
      'refeição pronta',
      'vegetais',
      'açaí',
      'lasanha congelada',
      'steaks',
      'picolé',
      'mandioca',
      'salgadinhos congelados',
      'frutas congeladas',
      'peixe congelado',
      'anéis de cebola',
      'tortas congeladas',
      'sorvete de massa'
    ],
    'Bebê': [
      'fralda',
      'lenço umedecido',
      'fórmula infantil',
      'pomada',
      'chupeta',
      'mamadeira',
      'shampoo bebê',
      'papinha',
      'banho',
      'cuidados',
      'condicionador bebê',
      'talco bebê',
      'colônia bebê',
      'mordedor',
      'babador',
      'sabonete líquido bebê',
      'hastes seguras',
      'copo de treinamento',
      'roupa de bebê',
      'brinquedo educativo'
    ],
    'Saúde e Suplementos': [
      'whey protein',
      'creatina',
      'vitamina',
      'ômega 3',
      'pré-treino',
      'barra de proteína',
      'colágeno',
      'emagrecimento',
      'performance',
      'massa',
      'bcaa',
      'glutamina',
      'multivitamínico',
      'hipercalórico',
      'albumina',
      'suplemento vegano',
      'termogênico',
      'pastilha de vitamina c',
      'magnésio',
      'zma'
    ],
    'Saudáveis/Especiais': [
      'sem glúten',
      'diet',
      'orgânico',
      'granola',
      'vegano',
      'integral',
      'castanhas',
      'zero lactose',
      'chia',
      'linhaça',
      'leite de amêndoas',
      'açúcar mascavo',
      'melado de cana',
      'quinoa',
      'tâmara',
      'aveia',
      'pasta de amendoim',
      'sal rosa',
      'biscoito de arroz',
      'snack saudável'
    ],
    'Farmácia': [
      'medicamento',
      'curativo',
      'termômetro',
      'primeiros socorros',
      'analgésico',
      'vitamina',
      'máscara',
      'álcool em pó',
      'antisséptico',
      'gaze',
      'band-aid',
      'esparadrapo',
      'soro fisiológico',
      'anti-inflamatório',
      'antiácido',
      'preservativo',
      'teste de gravidez',
      'algodão em bola',
      'pastilha garganta',
      'repelente'
    ],
    'Perfumaria': [
      'maquiagem',
      'perfume',
      'creme facial',
      'hidratante',
      'esmaltes',
      'protetor solar',
      'estética',
      'beleza',
      'batom',
      'máscara',
      'base facial',
      'rímel',
      'delineador',
      'removedor de esmalte',
      'água micelar',
      'sérum',
      'óleo corporal',
      'bronzeador',
      'corretivo',
      'fixador'
    ],
    'Floricultura': [
      'flores',
      'vaso',
      'adubo',
      'terra',
      'plantas',
      'presente',
      'buquê',
      'jardinagem',
      'semente',
      'decoração',
      'orquídea',
      'suculenta',
      'rosa',
      'ferramenta jardim',
      'regador',
      'cachepô',
      'folhagem',
      'pesticida natural',
      'substrato',
      'muda'
    ],
    'Casa e Utensílios': [
      'panela',
      'talher',
      'copo',
      'prato',
      'organizador',
      'assadeira',
      'pote',
      'limpeza profunda',
      'cozinha',
      'decorativo',
      'frigideira',
      'abridor',
      'escorredor',
      'tábua de carne',
      'jarra',
      'xícara',
      'tupperware',
      'peneira',
      'fouet',
      'ralador'
    ],
    'Papelaria': [
      'caderno',
      'caneta',
      'papel A4',
      'pasta',
      'lápis',
      'borracha',
      'mochila',
      'escritório',
      'escolar',
      'envelope',
      'corretivo',
      'canetinha',
      'tesoura',
      'grampeador',
      'fita adesiva',
      'calculadora',
      'bloco de notas',
      'apontador',
      'marca texto',
      'régua'
    ],
    'Eletro e Informática': [
      'mouse',
      'teclado',
      'fone de ouvido',
      'carregador',
      'cabo usb',
      'pilha',
      'bateria',
      'eletroportáteis',
      'ventilador',
      'suporte',
      'caixa de som',
      'pendrive',
      'power bank',
      'roteador',
      'headset',
      'liquidificador',
      'batedeira',
      'sanduicheira',
      'ferro de passar',
      'cafeteira'
    ],
    'Ferramentas e Jardim': [
      'martelo',
      'chave de fenda',
      'mangueira',
      'vaso',
      'trena',
      'parafuso',
      'alicates',
      'jardim',
      'reforma',
      'manutenção',
      'furadeira',
      'prego',
      'buchas',
      'serrote',
      'luva de proteção',
      'escada',
      'tinta',
      'pincel',
      'chave inglesa',
      'nível'
    ],
    'Vestuário': [
      'camiseta',
      'meia',
      'chinelo',
      'cueca',
      'calcinha',
      'bermuda',
      'pijama',
      'acessórios',
      'moda',
      'básico',
      'regata',
      'top',
      'shorts',
      'moletom',
      'boné',
      'cinto',
      'sandália',
      'sapatilha',
      'calça',
      'agasalho'
    ],
    'Brinquedos e Jogos': [
      'boneca',
      'carrinho',
      'tabuleiro',
      'quebra-cabeça',
      'educativo',
      'pelúcia',
      'infantil',
      'diversão',
      'card game',
      'lego',
      'massinha',
      'bolinha de gude',
      'iôiô',
      'piscina de bolinha',
      'fantoche',
      'slime',
      'bicicleta',
      'patins',
      'lançador',
      'quebra-cabeça 3d'
    ],
    'Tabacaria': [
      'isqueiro',
      'seda',
      'tabaco',
      'carvão',
      'essência',
      'palheiro',
      'filtro',
      'narguilé',
      'acessórios',
      'fumo',
      'dichavador',
      'cinzeiro',
      'piteira',
      'charuto',
      'fluido isqueiro',
      'bolador',
      'maçarico',
      'tabaco orgânico',
      'cliper',
      'porta cigarro'
    ],
    'Festas e Decoração': [
      'balão',
      'descartáveis',
      'enfeite',
      'velas festa',
      'painel',
      'lembrancinha',
      'confeitaria',
      'aniversário',
      'fantasia',
      'temático',
      'copo descartável',
      'prato descartável',
      'toalha de mesa',
      'confete',
      'serpentina',
      'chapéu de festa',
      'painel decorativo',
      'cachepô festa',
      'marshmallow festa',
      'kit festa'
    ],
    'Automotivo': [
      'óleo motor',
      'cera',
      'aditivo',
      'aromatizante',
      'limpeza carro',
      'estopa',
      'pneu',
      'palheta',
      'fluido',
      'manutenção',
      'shampoo automotivo',
      'pretinho',
      'limpa pneu',
      'silicone líquido',
      'chave de roda',
      'triângulo',
      'extintor',
      'macaco',
      'fusível',
      'água radiador'
    ],
    'Outros': [
      'diversos',
      'variados',
      'utilidades',
      'geral',
      'sem categoria',
      'oferta',
      'novidade',
      'importado',
      'presente',
      'promocional',
      'exclusivo',
      'queima de estoque',
      'lançamento',
      'mais vendidos',
      'sustentável',
      'econômico',
      'atacado',
      'varejo',
      'premium',
      'colecionável'
    ],
  };
}
