// models/tags_helper.dart

class TagsHelper {
  static const Map<String, List<String>> sugestoesPorCategoria = {
    'mercearia': [
      'básico',
      'grão',
      'cozinha',
      'tempero',
      'integral',
      'massas',
      'conservas',
      'enlatados',
      'óleo',
      'vinagre',
      'farinha',
      'café',
      'chá',
      'açúcar',
      'adoçante',
      'sem glúten',
      'vegano',
      'bala',
    ],
    'bebidas': [
      'gelada',
      'refrigerante',
      'suco',
      'alcoólico',
      'zero açúcar',
      'destilado',
      'cerveja',
      'vinho',
      'espumante',
      'energético',
      'isotônico',
      'água',
      'chá pronto',
      'leite',
      'achocolatado',
    ],
    'limpeza': [
      'casa',
      'detergente',
      'desinfetante',
      'roupa',
      'banheiro',
      'cozinha',
      'multiuso',
      'amaciante',
      'sabão em pó',
      'esponja',
      'inseticida',
      'ododorizador',
      'alvejante',
      'desengordurante',
    ],
    'higiene': [
      'pessoal',
      'banho',
      'dental',
      'cabelo',
      'perfumaria',
      'sabonete',
      'shampoo',
      'condicionador',
      'creme dental',
      'desodorante',
      'fio dental',
      'absorvente',
      'papel higiênico',
      'barba',
      'cotonete',
    ],
    'hortifruti': [
      'fresco',
      'orgânico',
      'fruta',
      'legume',
      'verdura',
      'folhas',
      'raiz',
      'tubérculo',
      'tempero fresco',
      'ovos',
      'saudável',
      'natural',
    ],
    'acougue': [
      'carne bovina',
      'frango',
      'suíno',
      'peixe',
      'frutos do mar',
      'churrasco',
      'bife',
      'moída',
      'espetinho',
      'congelado',
      'fresco',
    ],
    'padaria': [
      'pão',
      'bolo',
      'doce',
      'salgado',
      'biscoito',
      'bolacha',
      'café da manhã',
      'lanche',
      'artesanal',
      'confeitaria',
    ],
    'frios': [
      'queijo',
      'presunto',
      'salame',
      'iogurte',
      'manteiga',
      'requeijão',
      'margarina',
      'sobremesa láctea',
      'fatiado',
    ],
    'petshop': [
      'cão',
      'gato',
      'ração',
      'petisco',
      'higiene pet',
      'brinquedo',
      'areia sanitária',
      'filhote',
      'adulto',
      'castrado',
    ],
    'doces': [
      'doce',
      'chiclete',
      'pirulito',
      'goma',
      'pastilha',
      'chocolate',
      'bombom',
      'gelatina',
      'amendoim',
      'snack doce',
      'importado',
      'sem açúcar',
      'infantil',
    ],
    'outros': ['utilidades', 'bazar', 'presente', 'papelaria', 'festa'],
  };
}
